import os

# Folders (executed from root folder)
CWD = os.getcwd()

# ONNX metadata properties class names key
ONNX_METADATA_CLASS_NAMES_KEY = 'names'

# YOLO model name
YOLO_NAME = 'steel_bot'
YOLO_2C_NAME = 'steel_bot_2c'
YOLO_4C_NAME = 'steel_bot_4c'

# Number of augmentations
YOLO_NUM_AUGMENTATIONS = 10

# Epochs
YOLO_EPOCHS = 100

# YOLO folders
YOLO = os.path.join(CWD, 'yolo')
YOLO_REPO = 'ultralytics/ultralytics'
YOLO_DATASET = os.path.join(YOLO, 'dataset')

# Yolo folders common suffixes and prefixes
YOLO_TO_PROCESS = 'to_process'
YOLO_PROCESSED = 'processed'

# YOLO dataset main folders
YOLO_DATASET_ORIGINAL = os.path.join(YOLO_DATASET, 'original')
YOLO_DATASET_RESIZED = os.path.join(YOLO_DATASET, 'resized')
YOLO_DATASET_LABELED_2C = os.path.join(YOLO_DATASET, 'labeled_2c')
YOLO_DATASET_LABELED_4C = os.path.join(YOLO_DATASET, 'labeled_4c')
YOLO_DATASET_AUGMENTED_2C = os.path.join(YOLO_DATASET, 'augmented_2c')
YOLO_DATASET_AUGMENTED_4C = os.path.join(YOLO_DATASET, 'augmented_4c')
YOLO_DATASET_ORGANIZED_2C = os.path.join(YOLO_DATASET, 'organized_2c')
YOLO_DATASET_ORGANIZED_4C = os.path.join(YOLO_DATASET, 'organized_4c')

# YOLO dataset subfolders to process and processed
YOLO_DATASET_ORIGINAL_TO_PROCESS = os.path.join(YOLO_DATASET_ORIGINAL, YOLO_TO_PROCESS)
YOLO_DATASET_ORIGINAL_PROCESSED = os.path.join(YOLO_DATASET_ORIGINAL, YOLO_PROCESSED)
YOLO_DATASET_RESIZED_TO_PROCESS = os.path.join(YOLO_DATASET_RESIZED, YOLO_TO_PROCESS)
YOLO_DATASET_RESIZED_PROCESSED = os.path.join(YOLO_DATASET_RESIZED, YOLO_PROCESSED)
YOLO_DATASET_LABELED_2C_TO_PROCESS = os.path.join(YOLO_DATASET_LABELED_2C, YOLO_TO_PROCESS)
YOLO_DATASET_LABELED_2C_PROCESSED = os.path.join(YOLO_DATASET_LABELED_2C, YOLO_PROCESSED)
YOLO_DATASET_LABELED_4C_TO_PROCESS = os.path.join(YOLO_DATASET_LABELED_4C, YOLO_TO_PROCESS)
YOLO_DATASET_LABELED_4C_PROCESSED = os.path.join(YOLO_DATASET_LABELED_4C, YOLO_PROCESSED)
YOLO_DATASET_AUGMENTED_2C_TO_PROCESS = os.path.join(YOLO_DATASET_AUGMENTED_2C, YOLO_TO_PROCESS)
YOLO_DATASET_AUGMENTED_2C_PROCESSED = os.path.join(YOLO_DATASET_AUGMENTED_2C, YOLO_PROCESSED)
YOLO_DATASET_AUGMENTED_4C_TO_PROCESS = os.path.join(YOLO_DATASET_AUGMENTED_4C, YOLO_TO_PROCESS)
YOLO_DATASET_AUGMENTED_4C_PROCESSED = os.path.join(YOLO_DATASET_AUGMENTED_4C, YOLO_PROCESSED)
YOLO_DATASET_ORGANIZED_2C_TO_PROCESS = os.path.join(YOLO_DATASET_ORGANIZED_2C, YOLO_TO_PROCESS)
YOLO_DATASET_ORGANIZED_2C_PROCESSED = os.path.join(YOLO_DATASET_ORGANIZED_2C, YOLO_PROCESSED)
YOLO_DATASET_ORGANIZED_4C_TO_PROCESS = os.path.join(YOLO_DATASET_ORGANIZED_4C, YOLO_TO_PROCESS)
YOLO_DATASET_ORGANIZED_4C_PROCESSED = os.path.join(YOLO_DATASET_ORGANIZED_4C, YOLO_PROCESSED)

# YOLO model folders
BEST_ONNX = 'best.onnx'
BEST_PT = 'best.pt'
BEST_TENSOR_RT_QUANTIZED = 'best.engine'
YOLO_RUNS = os.path.join(YOLO, 'runs')
YOLO_RUNS_4C_WEIGHTS = os.path.join(YOLO_RUNS, YOLO_4C_NAME, 'weights')
YOLO_RUNS_4C_WEIGHTS_BEST_ONNX = os.path.join(YOLO_RUNS_4C_WEIGHTS, BEST_ONNX)
YOLO_RUNS_4C_WEIGHTS_BEST_PT = os.path.join(YOLO_RUNS_4C_WEIGHTS, BEST_PT)
YOLO_RUNS_4C_WEIGHTS_BEST_TENSOR_RT_QUANTIZED = os.path.join(YOLO_RUNS_4C_WEIGHTS, BEST_TENSOR_RT_QUANTIZED)
YOLO_RUNS_2C_WEIGHTS = os.path.join(YOLO_RUNS, YOLO_2C_NAME, 'weights')
YOLO_RUNS_2C_WEIGHTS_BEST_ONNX = os.path.join(YOLO_RUNS_2C_WEIGHTS, BEST_ONNX)
YOLO_RUNS_2C_WEIGHTS_BEST_PT = os.path.join(YOLO_RUNS_2C_WEIGHTS, BEST_PT)
YOLO_RUNS_2C_WEIGHTS_BEST_TENSOR_RT_QUANTIZED = os.path.join(YOLO_RUNS_2C_WEIGHTS, BEST_TENSOR_RT_QUANTIZED)

# YOLO zip folder
YOLO_ZIP = os.path.join(YOLO, 'zip')

# YOLO class colors
YOLO_2C_COLORS = {0: (68, 214, 44), 1: (238, 39, 55)}
YOLO_4C_COLORS = {0: (0, 51, 255), 1: (68, 214, 44), 2: (255, 102, 0), 3: (238, 39, 55)}

# Minimum confidence level and number of random images to test
YOLO_MINIMUM_CONFIDENCE_LEVEL = 0.70
YOLO_NUMBER_RANDOM_IMAGES = 10

# Arguments
ARGS_YOLO_FORMAT_PROP = 'format'
ARGS_YOLO_FORMAT = '--' + ARGS_YOLO_FORMAT_PROP
ARGS_YOLO_FORMAT_ONNX = 'onnx'
ARGS_YOLO_FORMAT_TFLITE = 'tflite'
ARGS_YOLO_FORMAT_TENSOR_RT = 'tensor_rt'
ARGS_YOLO_FORMAT_PT = 'pt'
ARGS_YOLO_QUANTIZED_PROP = 'quantized'
ARGS_YOLO_QUANTIZED = '--' + ARGS_YOLO_QUANTIZED_PROP
ARGS_YOLO_MODEL_PROP = 'model'
ARGS_YOLO_MODEL = '--' + ARGS_YOLO_MODEL_PROP
ARGS_YOLO_MODEL_2C = '2c'
ARGS_YOLO_MODEL_4C = '4c'
