site_name: Klevor
nav:
  - Nosotros: about.md
  - Electrónica:
    - Componentes:
      - Actuales: electronic/components/current.md
      - Viejos: electronic/components/old.md
    - Diagramas:
      - Diagramas de Conexiones: electronic/diagrams/wiring.md
  - Mecánica
  - Programación:
    - Lenguajes: programming/languages.md
    - Librerías: programming/libraries.md
    - Diagramas:
        - Diagramas de Flujo: programming/diagrams/flowcharts.md
  - GitHub: github.md
  - Videos: videos.md
markdown_extensions:
  - attr_list
use_directory_urls: false
extra_css:
  - stylesheets/extra.css

