site_name: Klevor
nav:
  - Nosotros: about.md
  - Electrónica:
    - Componentes:
      - Actuales: electronic/components/current.md
      - Previos: electronic/components/previous.md
    - Diagramas:
      - Diagramas de Conexiones: electronic/diagrams/wiring.md
  - Mecánica:
    - Prototipos:
      - Prototipo 1: mechanical/prototypes/prototype1.md
      - Prototipo 2: mechanical/prototypes/prototype2.md
      - Prototipo 3: mechanical/prototypes/prototype3.md
  - Programación:
    - Lenguajes: programming/languages.md
    - Librerías: programming/libraries.md
    - Diagramas:
        - Diagramas de Flujo: programming/diagrams/flowcharts.md
    - Glosario de Términos: programming/glossary.md
    - Guías:
        - Guía de CircuitPython: programming/guides/circuit-python.md
        - Guía de MicroPython: programming/guides/micro-python.md
        - Guía de Raspberry Pi: programming/guides/raspberry-pi.md
        - Guía de Detección de Objetos: programming/guides/object-detection.md
  - GitHub: github.md
  - Videos: videos.md
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - nl2br
plugins:
  - search
  - callouts

