//go:build tinygo && (rp2040 || rp2350)

package test

import "errors"

var (
	ErrNilPacketBytes                            = errors.New("nil packet bytes provided for parsing")
	ErrNilReport                                 = errors.New("nil report provided for parsing")
	ErrNilReportData                             = errors.New("nil report data provided for parsing")
	ErrNilBuffer                                 = errors.New("nil buffer provided for reading data")
	ErrNilPacketReader                           = errors.New("packet reader is nil, cannot read data")
	ErrNilPacketWriter                           = errors.New("packet writer is nil, cannot write data")
	ErrNilDataBuffer                             = errors.New("nil data buffer provided for reading data")
	ErrReportDataTooShort                        = errors.New("report data are too short to parse")
	ErrStabilityClassifierTooShort               = errors.New("stability classifier report bytes are too short to parse")
	ErrBufferTooShort                            = errors.New("buffer is too short to read the expected data")
	ErrBufferTooShortForHeader                   = errors.New("buffer is too short to read the packet header")
	ErrPacketDataTooShort                        = errors.New("packet data is too short to read the expected data")
	ErrInvalidReportIDForReportParsing           = "invalid report id for report parsing, expected %d, got %d"
	ErrUnknownReportID                           = errors.New("unknown report id received from sensor")
	ErrNilSensorReport                           = errors.New("nil sensor report provided for parsing")
	ErrCommandRequestTooManyArguments            = errors.New("command request cannot have more than 9 arguments")
	ErrFailedToReadSensorID                      = errors.New("failed to read sensor id from the device")
	ErrPacketTimeout                             = errors.New("packet read timeout exceeded")
	ErrNilPacket                                 = errors.New("nil packet provided for processing")
	ErrFailedToSaveCalibrationData               = errors.New("failed to save calibration data to the device")
	ErrInvalidReportIDForThreeDimensionalParsing = errors.New("invalid report id for three-dimensional parsing")
	ErrInvalidReportIDForFourDimensionalParsing  = errors.New("invalid report id for four-dimensional parsing")
	ErrInvalidChannel                            = errors.New("invalid channel number provided")
	ErrNoPacketAvailable                         = errors.New("no packet available to read from the i2c bus")
	ErrNilI2CBus                                 = errors.New("nil i2c bus provided for communication")
	ErrInvalidI2CAddress                         = errors.New("invalid i2c address provided")
	ErrNilDestinationBuffer                      = errors.New("nil destination buffer provided for uart read")
	ErrUnhandledUARTControlSHTPProtocol          = errors.New("unhandled uart control shtp protocol")
	ErrUARTEndMissing                            = errors.New("uart end byte missing from packet")
	ErrNilPacketHeaderString                     = errors.New("nil packet header string provided for parsing")
	ErrNilPacketString                           = errors.New("nil packet string provided for parsing")
	ErrNilPacketData                             = errors.New("nil packet data provided for parsing")
	ErrNilPacketBuffer                           = errors.New("nil packet buffer provided for parsing")
	ErrNilPacketHeader                           = errors.New("nil packet header provided for parsing")
	ErrNilPacketHeaderBuffer                     = errors.New("nil packet header buffer provided for parsing")
	ErrNilUARTBus                                = errors.New("nil uart bus provided for communication")
	ErrUARTTimeout                               = errors.New("uart read timeout exceeded")
	ErrNilSubcommandParams                       = errors.New("nil subcommand parameters provided")
)
