from opencv.image_augmentation import augment_dataset
from yolo.constants import YOLO_NUM_AUGMENTATIONS, YOLO_DATASET_LABELED_2C_PROCESSED, \
    YOLO_DATASET_LABELED_2C_TO_PROCESS, YOLO_DATASET_AUGMENTED_2C_TO_PROCESS

if __name__ == '__main__':
    augment_dataset(YOLO_DATASET_LABELED_2C_TO_PROCESS, YOLO_DATASET_AUGMENTED_2C_TO_PROCESS, YOLO_NUM_AUGMENTATIONS,
                    YOLO_DATASET_LABELED_2C_PROCESSED)
