import os

# Folders (executed from root folder)
CWD = os.getcwd()

# YOLO model name
YOLO_NAME = 'steel_bot'
YOLO_2C_NAME = 'steel_bot_2c'
YOLO_4C_NAME = 'steel_bot_4c'

# Number of augmentations
YOLO_NUM_AUGMENTATIONS = 10

# Epochs
YOLO_EPOCHS = 100

# YOLO folders
YOLO = os.path.join(CWD, 'yolo')
YOLO_REPO = 'ultralytics/ultralytics'
YOLO_DATASET = os.path.join(YOLO, 'dataset')

# Yolo folders common suffixes and prefixes
YOLO_TO_PROCESS = 'to_process'
YOLO_PROCESSED = 'processed'

# YOLO dataset main folders
YOLO_DATASET_ORIGINAL = os.path.join(YOLO_DATASET, 'original')
YOLO_DATASET_RESIZED = os.path.join(YOLO_DATASET, 'resized')
YOLO_DATASET_LABELED_2C = os.path.join(YOLO_DATASET, 'labeled_2c')
YOLO_DATASET_LABELED_4C = os.path.join(YOLO_DATASET, 'labeled_4c')
YOLO_DATASET_AUGMENTED_2C = os.path.join(YOLO_DATASET, 'augmented_2c')
YOLO_DATASET_AUGMENTED_4C = os.path.join(YOLO_DATASET, 'augmented_4c')
YOLO_DATASET_ORGANIZED_2C = os.path.join(YOLO_DATASET, 'organized_2c')
YOLO_DATASET_ORGANIZED_4C = os.path.join(YOLO_DATASET, 'organized_4c')

# YOLO dataset subfolders to process and processed
YOLO_DATASET_ORIGINAL_TO_PROCESS = os.path.join(YOLO_DATASET_ORIGINAL, YOLO_TO_PROCESS)
YOLO_DATASET_ORIGINAL_PROCESSED = os.path.join(YOLO_DATASET_ORIGINAL, YOLO_PROCESSED)
YOLO_DATASET_RESIZED_TO_PROCESS = os.path.join(YOLO_DATASET_RESIZED, YOLO_TO_PROCESS)
YOLO_DATASET_RESIZED_PROCESSED = os.path.join(YOLO_DATASET_RESIZED, YOLO_PROCESSED)
YOLO_DATASET_LABELED_2C_TO_PROCESS = os.path.join(YOLO_DATASET_LABELED_2C, YOLO_TO_PROCESS)
YOLO_DATASET_LABELED_2C_PROCESSED = os.path.join(YOLO_DATASET_LABELED_2C, YOLO_PROCESSED)
YOLO_DATASET_LABELED_4C_TO_PROCESS = os.path.join(YOLO_DATASET_LABELED_4C, YOLO_TO_PROCESS)
YOLO_DATASET_LABELED_4C_PROCESSED = os.path.join(YOLO_DATASET_LABELED_4C, YOLO_PROCESSED)
YOLO_DATASET_AUGMENTED_2C_TO_PROCESS = os.path.join(YOLO_DATASET_AUGMENTED_2C, YOLO_TO_PROCESS)
YOLO_DATASET_AUGMENTED_2C_PROCESSED = os.path.join(YOLO_DATASET_AUGMENTED_2C, YOLO_PROCESSED)
YOLO_DATASET_AUGMENTED_4C_TO_PROCESS = os.path.join(YOLO_DATASET_AUGMENTED_4C, YOLO_TO_PROCESS)
YOLO_DATASET_AUGMENTED_4C_PROCESSED = os.path.join(YOLO_DATASET_AUGMENTED_4C, YOLO_PROCESSED)
YOLO_DATASET_ORGANIZED_2C_TO_PROCESS = os.path.join(YOLO_DATASET_ORGANIZED_2C, YOLO_TO_PROCESS)
YOLO_DATASET_ORGANIZED_2C_PROCESSED = os.path.join(YOLO_DATASET_ORGANIZED_2C, YOLO_PROCESSED)
YOLO_DATASET_ORGANIZED_4C_TO_PROCESS = os.path.join(YOLO_DATASET_ORGANIZED_4C, YOLO_TO_PROCESS)
YOLO_DATASET_ORGANIZED_4C_PROCESSED = os.path.join(YOLO_DATASET_ORGANIZED_4C, YOLO_PROCESSED)

# YOLO model folders
BEST_ONNX = 'best.onnx'
BEST_PT = 'best.pt'
YOLO_RUNS = os.path.join(YOLO, 'runs')
YOLO_RUNS_4C_WEIGHTS = os.path.join(YOLO_RUNS, YOLO_4C_NAME, 'weights')
YOLO_RUNS_4C_WEIGHTS_BEST_ONNX = os.path.join(YOLO_RUNS_4C_WEIGHTS, BEST_ONNX)
YOLO_RUNS_4C_WEIGHTS_BEST_PT = os.path.join(YOLO_RUNS_4C_WEIGHTS, BEST_PT)
YOLO_RUNS_2C_WEIGHTS = os.path.join(YOLO_RUNS, YOLO_2C_NAME, 'weights')
YOLO_RUNS_2C_WEIGHTS_BEST_ONNX = os.path.join(YOLO_RUNS_2C_WEIGHTS, BEST_ONNX)
YOLO_RUNS_2C_WEIGHTS_BEST_PT = os.path.join(YOLO_RUNS_2C_WEIGHTS, BEST_PT)

# YOLO zip folder
YOLO_ZIP = os.path.join(YOLO, 'zip')
YOLO_TO_TRAIN_BASE_FILENAME = 'to_train'

# YOLO zip ignore directories
YOLO_ZIP_IGNORE_DIRS = ['runs', 'zip']

# YOLO class colors
YOLO_2C_COLORS = {0: (68, 214, 44), 1: (238, 39, 55)}
YOLO_4C_COLORS = {0: (0, 51, 255), 1: (68, 214, 44), 2: (255, 102, 0), 3: (238, 39, 55)}

# Minimum confidence level and number of random images to test
YOLO_MINIMUM_CONFIDENCE_LEVEL = 0.45
YOLO_NUMBER_RANDOM_IMAGES = 10