package usbcdc

import (
	tinygotypes "github.com/ralvarezdev/tinygo-types"
)

const (
	// ErrorCodeUSBCDCStartNumber is the starting number for USB CDC-related error codes.
	ErrorCodeUSBCDCStartNumber uint16 = 50
)

const (
	ErrorCodeUSBCDCNilHandler tinygotypes.ErrorCode = tinygotypes.ErrorCode(iota + ErrorCodeUSBCDCStartNumber)
	ErrorCodeUSBCDCNilOutgoingCategory
	ErrorCodeUSBCDCUnknownOutgoingCategory
	ErrorCodeUSBCDCNilIncomingCategory
	ErrorCodeUSBCDCUnknownIncomingCategory
	ErrorCodeUSBCDCInvalidMaxMessageDataLength
	ErrorCodeUSBCDCFailedToSendStartCharacter
	ErrorCodeBNO08XFailedToSendOutgoingCategory
	ErrorCodeUSBCDCFailedToSendControlCharacter
	ErrorCodeUSBCDCFailedToSendMessageContent
	ErrorCodeUSBCDCFailedToSendEndCharacter
	ErrorCodeBNO08XBufferTooShortForRawFloat64
	ErrorCodeBNO08XUnknownQuaternionIndex
	ErrorCodeBNO08XUnknownEulerDegreesIndex
	ErrorCodeUSBCDCUnknownIncomingStatus
	ErrorCodeUSBCDCUnknownOutgoingStatus
	ErrorCodeUSBCDCUnknownChallenge
	ErrorCodeBNO08XBufferTooShortForRawUint16
	ErrorCodeBNO08XBufferTooShortForRawUint8
	ErrorCodeUSBCDCConfirmationMessageTimeout
	ErrorCodeUSBCDCReadByteTimeout
	ErrorCodeUSBCDCFailedReadingFromSerial
	ErrorCodeUSBCDCFailedToConfigureUSBCDC
	ErrorCodeUSBCDCFailedToSendInitializationMessage
	ErrorCodeUSBCDCInvalidIncomingMessageDataLength
	ErrorCodeUSBCDCInvalidOutgoingMessageDataLength
	ErrorCodeUSBCDCReadMessageTimeout	
	ErrorCodeUSBCDCReceivedUnexpectedConfirmationMessage
)