package usbcdc

import (
	tinygotypes "github.com/ralvarezdev/tinygo-types"
)

const (
	// ErrorCodeUSBCDCStartNumber is the starting number for USB CDC-related error codes.
	ErrorCodeUSBCDCStartNumber uint16 = 50
)

const (
	ErrorCodeUSBCDCNilHandler tinygotypes.ErrorCode = tinygotypes.ErrorCode(iota + ErrorCodeUSBCDCStartNumber)
	ErrorCodeUSBCDCNilOutgoingCategory
	ErrorCodeUSBCDCUnknownOutgoingCategory
	ErrorCodeUSBCDCNilIncomingCategory
	ErrorCodeUSBCDCUnknownIncomingCategory
	ErrorCodeUSBCDCInvalidMaxMessageDataLength
	ErrorCodeUSBCDCFailedToSendStartByte
	ErrorCodeUSBCDCFailedToSendOutgoingCategory
	ErrorCodeUSBCDCFailedToSendControlByte
	ErrorCodeUSBCDCFailedToSendMessageContent
	ErrorCodeUSBCDCFailedToSendEndByte
	ErrorCodeUSBCDCBufferTooShortForRawFloat64
	ErrorCodeUSBCDCUnknownQuaternionIndex
	ErrorCodeUSBCDCUnknownEulerDegreesIndex
	ErrorCodeUSBCDCUnknownIncomingStatus
	ErrorCodeUSBCDCUnknownOutgoingStatus
	ErrorCodeUSBCDCUnknownChallenge
	ErrorCodeUSBCDCBufferTooShortForRawUint16
	ErrorCodeUSBCDCBufferTooShortForRawUint8
	ErrorCodeUSBCDCConfirmationMessageTimeout
	ErrorCodeUSBCDCReadByteTimeout
	ErrorCodeUSBCDCFailedReadingFromSerial
	ErrorCodeUSBCDCFailedToConfigureUSBCDC
	ErrorCodeUSBCDCFailedToSendInitializationMessage
	ErrorCodeUSBCDCInvalidIncomingMessageDataLength
	ErrorCodeUSBCDCInvalidOutgoingMessageDataLength
	ErrorCodeUSBCDCReadMessageTimeout	
	ErrorCodeUSBCDCReceivedUnexpectedConfirmationMessage
)