//go:build tinygo && (rp2040 || rp2350)

package tinygo_bno08x

import (
	tinygotypes "github.com/ralvarezdev/tinygo-types"
)

const (
	// ErrorCodeBNO08XStartNumber is the starting number for BNO08X-related error codes.
	ErrorCodeBNO08XStartNumber uint16 = 5000
)

const (
	ErrorCodeBNO08XPacketBufferIndexOutOfRange tinygotypes.ErrorCode = tinygotypes.ErrorCode(iota + ErrorCodeBNO08XStartNumber)
	ErrorCodeBNO08XInvalidChannelNumber
	ErrorCodeBNO08XNilPacketReader
	ErrorCodeBNO08XNilPacketWriter
	ErrorCodeBNO08XNilUARTBus
	ErrorCodeBNO08XFailedToConfigureUART
	ErrorCodeBNO08XFailedToResetUARTRVC
	ErrorCodeBNO08XUARTRVCNilFrame
	ErrorCodeBNO08XUARTRVCFrameTooShort
	ErrorCodeBNO08XUARTRVCInvalidChecksum
	ErrorCodeBNO08XUARTRVCByteTimeout
	ErrorCodeBNO08XUARTRVCFailedToReadByte
	ErrorCodeBNO08XFailedToParseFrame
	ErrorCodeBNO08XUARTRVCUARTTimeout
	ErrorCodeBNO08XFailedToCreatePacket
	ErrorCodeBNO08XFailedToSetUARTFormat
	ErrorCodeBNO08XFailedToCreatePacketReader
	ErrorCodeBNO08XFailedToCreatePacketWriter
	ErrorCodeBNO08XUARTByteTimeout
	ErrorCodeBNO08XUARTFailedToReadByte
	ErrorCodeBNO08XFailedToResetBNO08X
	ErrorCodeBNO08XNilPacketBuffer
	ErrorCodeBNO08XFailedToGetExpectedReportLength
	ErrorCodeBNO08XInvalidReportLength
	ErrorCodeBNO08XFailedToGetReportID
	ErrorCodeBNO08XInsertCommandRequestReportBufferTooShort
	ErrorCodeBNO08XInsertCommandRequestReportTooManyArguments
	ErrorCodeBNO08XUnknownReportID
	ErrorCodeBNO08XFailedToCreatePacketFromBuffer
	ErrorCodeBNO08XFailedToCreateReportFromPacketBuffer
	ErrorCodeBNO08XInvalidReportIDToParseReport
	ErrorCodeBNO08XInvalidReportStabilityClassificationUint8
	ErrorCodeBNO08XInvalidReportActivityUint8
	ErrorCodeBNO08XInvalidReportIDForFourDimensionalParsing
	ErrorCodeBNO08XInvalidReportIDForThreeDimensionalParsing
	ErrorCodeBNO08XInvalidReportAccuracyStatusUint8
	ErrorCodeBNO08XSensorReportDataTooShort
	ErrorCodeBNO08XNoPacketAvailable
	ErrorCodeBNO08XInvalidReportDataLength
	ErrorCodeBNO08XUARTEndMissing
	ErrorCodeBNO08XPacketHeaderBufferTooShort
	ErrorCodeBNO08XNilDestinationBuffer
	ErrorCodeBNO08XInvalidStartOrEndIndex
	ErrorCodeBNO08XNilPacketData
	ErrorCodeBNO08XCommandRequestReportNilBuffer
	ErrorCodeBNO08XNilReportData
	ErrorCodeBNO08XNilCommandRequestReportParameters
	ErrorCodeBNO08XPacketDataTooShort
	ErrorCodeBNO08XI2CFailedToProbeDevice
	ErrorCodeBNO08XI2CFailedToProbeDeviceRepeatly
	ErrorCodeBNO08XNilI2CBus
	ErrorCodeBNO08XInvalidI2CAddress
	ErrorCodeBNO08XFailedToConfigureI2C
	ErrorCodeBNO08XI2CFailedToWritePacketHeaderBuffer
	ErrorCodeBNO08XI2CFailedToWritePacketPacketBuffer
	ErrorCodeBNO08XPacketBufferTooShortForPacketHeader
	ErrorCodeBNO08XPacketBufferTooShortForPacket
	ErrorCodeBNO08XI2CFailedToReadRequestedDataLength
	ErrorCodeBNO08XInvalidPacketSize
	ErrorCodeBNO08XNilSPIBus
	ErrorCodeBNO08XFailedToConfigureSPI
	ErrorCodeBNO08XFailedToWakeUpSPI
	ErrorCodeBNO08XSPIFailedToWritePacketHeaderBuffer
	ErrorCodeBNO08XSPIFailedToWritePacketPacketBuffer
	ErrorCodeBNO08XSPIFailedToReadRequestedDataLength
	ErrorCodeBNO08XFailedToEnableDependencyFeature
	ErrorCodeBNO08XFailedToEnableFeature
	ErrorCodeBNO08XFailedToBeginCalibration
	ErrorCodeBNO08XNilSubcommandParams
	ErrorCodeBNO08XFailedToInsertCommandRequestReport
	ErrorCodeBNO08XFailedToSendMeCommandRequestPacket
	ErrorCodeBNO08XFailedToSendCommandRequestPacketToSaveCalibrationData
	ErrorCodeBNO08XFailedToSaveCalibrationData
	ErrorCodeBNO08XFailedToSendResetCommandRequestPacket
	ErrorCodeBNO08XFailedToReadSensorID
	ErrorCodeBNO08XFailedToSendProductIDRequestPacket
	ErrorCodeBNO08XWaitingForPacketTimedOut
	ErrorCodeBNO08XMismatchedPacketDataLength
	ErrorCodeBNO08XFailedToSaveDynamicCalibrationData
	ErrorCodeBNO08XFailedToParseGetFeatureReport
	ErrorCodeBNO08XFailedToParseSensorID
	ErrorCodeBNO08XFailedToParseRawMagnetometerReport
	ErrorCodeBNO08XFailedToParseStepCounterReport
	ErrorCodeBNO08XFailedToParseShakeReport
	ErrorCodeBNO08XFailedToParseStabilityClassifierReport
	ErrorCodeBNO08XFailedToParseActivityClassifierReport
	ErrorCodeBNO08XFailedToParseMagnetometerReport
	ErrorCodeBNO08XFailedToParseRotationVectorReport
	ErrorCodeBNO08XFailedToParseGeomagneticRotationVectorReport
	ErrorCodeBNO08XFailedToParseGameRotationVectorReport
	ErrorCodeBNO08XFailedToParseAccelerometerReport
	ErrorCodeBNO08XFailedToParseLinearAccelerationReport
	ErrorCodeBNO08XFailedToParseGravityReport
	ErrorCodeBNO08XFailedToParseGyroscopeReport
	ErrorCodeBNO08XFailedToParseRawGyroscopeReport
	ErrorCodeBNO08XFailedToParseRawAccelerometerReport
	ErrorCodeBNO08XFailedToGetReportLengthForTheGivenReportID
	ErrorCodeBNO08XUnprocessableBatchBytes
	ErrorCodeBNO08XI2CFailedToReadPacketHeader
	ErrorCodeBNO08XSPIFailedToReadPacketHeader
	ErrorCodeBNO08XUnhandledUARTControlSHTPProtocol
	ErrorCodeBNO08XNilBNO08XInstance
	ErrorCodeBNO08XSetFeatureEnableReportDataNilBuffer
	ErrorCodeBNO08XSetFeatureEnableReportDataBufferTooShort
	ErrorCodeBNO08XNilPacketHeaderBuffer
	ErrorCodeBNO08XReportHeaderBufferTooShort
	ErrorCodeBNO08XNilWaitForPacketFunction
	ErrorCodeBNO08XInvalidMode
	ErrorCodeBNO08XUnknownModeAttemptingSoftwareReset
)
